# 정렬
- 배열 값을 기준에 따라 순서대로 배치하는 작업임
- 오름차순/내림차순 정렬 가능함
- 원본 유지 여부 확인 필요함


In [2]:
import numpy as np

In [3]:
# np.sort(ndarray)
# - 정렬된 새 배열 반환
# - 월본 배열 유지
# - 원본 데이터 유지 여부는 데이터 전처리에 있어 중요한 부분이다
arr = np.random.randint(1,11,10)
print("arr:",arr)
print("np.sort(arr):",np.sort(arr)) # 정렬
print("arr:",arr)                   # 원본 유지 확인

arr: [ 1  1 10  3  7  6  4  7  3  1]
np.sort(arr): [ 1  1  1  3  3  4  6  7  7 10]
arr: [ 1  1 10  3  7  6  4  7  3  1]


In [4]:
# 내림차순(역순정렬) -> 슬라이싱 방식 이용
np.sort(arr)[::-1]

array([10,  7,  7,  6,  4,  3,  3,  1,  1,  1], dtype=int32)

In [8]:
# 2차원 배열 형태의 데이터 정렬
# - axis에 따라 정렬 기준이 달라짐
# - axis = None : 전체 (1차원으로 변경 후 전체 정렬)
# - axis = 0 : 행 방향 정렬 (세로)
# - axis = 1 : 열 방향 정렬 (가로)
np.random.seed(1)
arr = np.random.randint(1,15,(3,4))
print(arr)
print("np.sort(arr,axis=None):\n",np.sort(arr,axis=None))
print("np.sort(arr,axis=0):\n",np.sort(arr,axis=0))
print("np.sort(arr,axis=1):\n",np.sort(arr,axis=1))

[[ 6 12 13  9]
 [10 12  6  1]
 [ 1  2 13  8]]
np.sort(arr,axis=None):
 [ 1  1  2  6  6  8  9 10 12 12 13 13]
np.sort(arr,axis=0):
 [[ 1  2  6  1]
 [ 6 12 13  8]
 [10 12 13  9]]
np.sort(arr,axis=1):
 [[ 6  9 12 13]
 [ 1  6 10 12]
 [ 1  2  8 13]]


## np.argsort()
- 배열 요소를 정렬했을 때의 인덱스를 반환함
- 정렬된 값 자체가 아니라 정렬 순서임
- 실제 정렬값은 `arr[indices]`처럼 다시 인덱싱해야 함


In [10]:
# argsort()의 결과값은 정렬 순서를 만드는 인덱스이다

arr = np.array([40,10,20,30])
indices = np.argsort(arr)
print(indices)
print(arr[indices])

[1 2 3 0]
[10 20 30 40]


In [10]:
# 역순정렬

arr = np.array([40,10,20,30])
indices = np.argsort(-arr)  # arr * -1
print(indices)
print(arr[indices])

[1 2 3 0]
[10 20 30 40]


In [13]:
# 2차원 argsort(axis=0)
arr = np.array([[30,10,20],
                [60,40,50]])
indices = np.argsort(arr,axis=0)    # 행방향 정렬
print(indices)

[[0 0 0]
 [1 1 1]]


In [14]:
# 2차원 argsort(axis=1)
indices = np.argsort(arr,axis=1)    # 열방향 정렬
print(indices)

[[1 2 0]
 [1 2 0]]


In [15]:
# 각 배열의 같은 인덱스 요소가 한 학생의 이름, 점수를 나타내고 있음
# 학생의 이름을 점수 내림차순으로 정렬
names = np.array(['홍길동', '신사임당', '이순신', '유관순'])
scores = np.array([90, 30, 50, 70])

# 결과: ['홍길동' '유관순' '이순신' '신사임당']
indices = np.argsort(-scores)
print(names[indices])

['홍길동' '유관순' '이순신' '신사임당']


In [16]:
# 우선순위에 따른 작업 정렬(작은 수일수록 높은 우선 순위)
priorities = np.array([3, 1, 2, 5, 4])
tasks = np.array(["Task A", "Task B", "Task C", "Task D", "Task E"])

# 결과: ["Task B" "Task C" "Task A" "Task E" "Task D"]
indices = np.argsort(priorities)
print(tasks[indices])

['Task B' 'Task C' 'Task A' 'Task E' 'Task D']
